Sapoepsilon/adj 68 research how could you know if the person is done talking
sapoepsilon/twilio-server-wss pull request #2
Opened 2023-12-12 07:06 UTC by sapoepsilon

2023-12-21 16:45 UTC, KamronBegmatov requested changes
@sapoepsilon

2023-12-21 16:45 UTC, KamronBegmatov commented on server.js
>  initializeWebSocketServer();
In terms of code organization and readability, it's often a good practice to place the most important or high-level code at the top of the file and helper functions or details below. This way, someone reading your code can get an immediate sense of what the module does without having to scroll through all the implementation details.

2023-12-21 16:45 UTC, KamronBegmatov commented on services/processAudioData.js
> +
redundant

2023-12-21 16:45 UTC, KamronBegmatov commented on twilio-media-server/TwilioMediaStreamSaveAudioFile.js
> +
redundant line

2023-12-21 16:45 UTC, KamronBegmatov commented on twilio-media-server/TwilioMediaStreamSaveAudioFile.js
> +
redundant line

2023-12-21 16:45 UTC, KamronBegmatov commented on twilio-media-server/TwilioMediaStreamSaveAudioFile.js
> +import {saveLocation} from "../server.js";
need empty line

2023-12-21 16:45 UTC, KamronBegmatov commented on twilio-media-server/TwilioMediaStreamSaveAudioFile.js
> +            else if (res === VAD.Event.ERROR) {
move please to the previous line, as on 132, 128, so that it looks nice and clean

2023-12-21 16:45 UTC, KamronBegmatov commented on twilio-media-server/TwilioMediaStreamSaveAudioFile.js
> +    }
need empty line after this

2023-12-21 16:45 UTC, KamronBegmatov commented on utils/sendToWhisperServer.js
> -        } else {
this style actually was better, but it's just a choice of style, so no need. if you prefer one-liner, then fine

2023-12-21 16:45 UTC, KamronBegmatov commented on web-client/app.js
> +    const ws = new WebSocket('wss://eeb5-69-162-230-182.ngrok-free.app');
maybe it's better to move WSS URL to .env, as if someone else uses ngrok, changes url here, then this file will go to commit every time

2023-12-21 16:45 UTC, KamronBegmatov commented on web-client/app.js
> +    ws.onopen = () => {
onOpen(), onClose, onError would be more readable maybe, or if it's websocket's method, then no choice

2023-12-21 16:45 UTC, KamronBegmatov commented on web-client/app.js
> +        } else if (mediaRecorder) {
maybe just else

2023-12-23 20:29 UTC, sapoepsilon commented on web-client/app.js
> +    const ws = new WebSocket('wss://eeb5-69-162-230-182.ngrok-free.app');
I will leave it for now. The web ui will be used for debugging puposes down the line. However, it doesn't work right now since the server expects analog audio, and web server gives digital audio.

2023-12-23 20:30 UTC, sapoepsilon commented on web-client/app.js
> +    ws.onopen = () => {
These are good comments. I will revisit them, once I will work on web-ui again.

2023-12-25 03:06 UTC, KamronBegmatov approved these changes

2023-12-25 03:06 UTC, KamronBegmatov commented on twilio-media-server/TwilioMediaStreamSaveAudioFile.js
> +import {saveLocation} from "../server.js";
FYI @sapoepsilon

2023-12-27 02:47 UTC, merged